host:        127.0.0.1
port:        4000

name:        "Welcome to the Void"
markdown:    kramdown
highlighter: rouge

permalink:   /news/:year/:month/:title.html

snow:        0

gems:
  - jekyll-redirect-from
